version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - devops-net

  localstack:
    image: localstack/localstack:0.12.17
    container_name: localstack
    ports:
      - "4566:4566" # Edge port
      - "4571:4571"
    environment:
      - SERVICES=s3,iam,sts,dynamodb
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_S3_PATH_STYLE=1
      - USE_SSL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge 